### PR TITLE
Add ppa:zoogie/sdl2-snapshots to whitelist

### PR DESCRIPTION
**Pull request by forestbelton**

### CODE REVIEW

**Comment by Agrosis** [comment]
+1

**Comment by StoneCypher** [comment]
+1

**Comment by vincehoward** [comment]
+1

**Comment by jahan-addison** [comment]
+1

**Comment by DrMcCoy** [comment]
+1

**Comment by madebr** [comment]
+1

**Comment by LiquidityC** [comment]
+1

**Comment by miniupnp** [comment]
:+1:

**Comment by bagage** [comment]
:+1:

**Comment by dankan1890** [comment]
+1

**Comment by mafagafogigante** [comment]
I also want this.

**Comment by dessant** [comment]
Ref: https://github.com/travis-ci/apt-source-whitelist/issues/45.

**Comment by StoneCypher** [comment]
image

**Comment by forestbelton** [comment]
Closing this since it's been over 3 years and maintainers don't seem to have any interest.

**Pull request closed without merging**
