### PR TITLE
add llvm-toolchain-trusty-8 & llvm-toolchain-xenial-8

### PR DESCRIPTION
**Pull request by sylvestre**
Just like https://github.com/travis-ci/apt-source-safelist/pull/392

### CODE REVIEW

**Comment by sylvestre** [comment]
cc @BanzaiMan

**Comment by sylvestre** [comment]
ping @BanzaiMan thanks

**Comment by nafur** [comment]
we also would like to have that!

**Comment by BanzaiMan** [comment]
In general, you no longer need this repository. You can use the addon, as described in https://docs.travis-ci.com/user/installing-dependencies#installing-packages-with-the-apt-addon

**Pull request merged**
