### PR TITLE
add llvm toolchain 4.0 for precise

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by sylvestre** [comment]
@BanzaiMan Can you merge that? Thanks

**Comment by sylvestre** [comment]
@BanzaiMan ping?

**Comment by SnirkImmington** [comment]
If you look at the readme, it seems they've given up:

> At this moment, we are unable to continue processing the APT sources requests. If you require a new source, please use `sudo: required` in your `.travis.yml` file.

If you need this for a container build try installing LLVM to a directory in `~` and modifying `$PATH`.

**Comment by eliaskosunen** [comment]
> If you look at the readme, it seems they've given up:
>
> > At this moment, we are unable to continue processing the APT sources requests. If you require a new source, please use sudo: required in your .travis.yml file.
>
> If you need this for a container build try installing LLVM to a directory in ~ and modifying $PATH.

That sucks. Does anyone know the specific reason for this?

**Pull request closed without merging**
