### PR TITLE
add llvm-toolchain-trusty-7

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by prince-chrismc** [comment]
Using this config manually I was able to build my project

**Comment by prsolucoes** [comment]
@BanzaiMan could you please merge that? Thanks

**Comment by prsolucoes** [comment]
I got error:

```

Setting APT mirror in /etc/apt/sources.list: http://archive.ubuntu.com/ubuntu/
Adding APT Sources
1.67s$ sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
gpg: keyring `/tmp/tmpls17f9tj/secring.gpg' created
gpg: keyring `/tmp/tmpls17f9tj/pubring.gpg' created
gpg: requesting key BA9EF27F from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpls17f9tj/trustdb.gpg: trustdb created
gpg: key BA9EF27F: public key "Launchpad Toolchain builds" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
0.07s$ curl -sSL "https://build.travis-ci.org/files/gpg/llvm-toolchain-trusty-7.asc" | sudo -E apt-key add -
gpg: no valid OpenPGP data found.
The command "curl -sSL "https://build.travis-ci.org/files/gpg/llvm-toolchain-trusty-7.asc" | sudo -E apt-key add -" failed and exited with 2 during .
Your build has been stopped.
```

**Comment by prsolucoes** [comment]
https://travis-ci.org/ezored/dependency-logger/jobs/437863294

**Comment by prince-chrismc** [comment]
seems like everything is working on my end =)

image

**Comment by prsolucoes** [comment]
Working when i added:

```
packages:
  - libstdc++-7-dev
```

But failling for gcc 6/7/8 because dont support **constexpr**. But is another problem.
https://travis-ci.org/ezored/dependency-logger/jobs/437916450

Thanks.

**Comment by hartwork** [comment]
@psi29a , the `.0` is the problem, try `llvm-toolchain-trusty-7` without `.0` as seen here: https://github.com/uriparser/uriparser/blob/master/.travis.yml#L11

**Comment by psi29a** [comment]
@hartwork thanks! :)

**Pull request merged**
